# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bbe475b4739754a70246784eb44c7f99b8676ad06546dc4577171b66f95cbad181c9934dcdde65128da35e4e01b9e600613c4724af90c904573a58c774e8130

test:
  secret_key_base: 7da88f4aa16fa0efa012879bc3f26c10908583ae993888296270b5a9d1e81f530feed0452001ff7c79fd271eff2ad4a93a674be429ec442949bd928b03a79aaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
